export interface FeatureFlags {
  FEATURE_WEATHER_SPOILAGE: boolean;
  FEATURE_MARKET_INTELLIGENCE: boolean;
  FEATURE_DEPARTURE_OPTIMIZER: boolean;
  FEATURE_COLD_CHAIN_BREAK_EVEN: boolean;
  FEATURE_GROUP_SHIPMENT: boolean;
  FEATURE_BACKHAUL: boolean;
  FEATURE_CALIBRATION: boolean;
  FEATURE_CARBON_ESTIMATE: boolean;
  FEATURE_SHIPMENT_TIMELINE: boolean;
  FEATURE_ALERTS: boolean;
  FEATURE_WHATSAPP_SHARE: boolean;
  FEATURE_VOICE_SIMPLE_MODE: boolean;
  FEATURE_DRIVER_APP: boolean;
  FEATURE_ADMIN_DASHBOARD: boolean;
}

export const config: FeatureFlags & {
  OPEN_METEO_BASE_URL: string;
  EMISSION_FACTOR_KG_PER_L: number;
  ADMIN_TOKEN: string;
} = {
  FEATURE_WEATHER_SPOILAGE: true,
  FEATURE_MARKET_INTELLIGENCE: true,
  FEATURE_DEPARTURE_OPTIMIZER: true,
  FEATURE_COLD_CHAIN_BREAK_EVEN: true,
  FEATURE_GROUP_SHIPMENT: true,
  FEATURE_BACKHAUL: true,
  FEATURE_CALIBRATION: true,
  FEATURE_CARBON_ESTIMATE: true,
  FEATURE_SHIPMENT_TIMELINE: true,
  FEATURE_ALERTS: true,
  FEATURE_WHATSAPP_SHARE: true,
  FEATURE_VOICE_SIMPLE_MODE: true,
  FEATURE_DRIVER_APP: true,
  FEATURE_ADMIN_DASHBOARD: true,
  OPEN_METEO_BASE_URL: 'https://api.open-meteo.com/v1/forecast',
  EMISSION_FACTOR_KG_PER_L: 2.68,
  ADMIN_TOKEN: 'marudhamx-admin-secret-2026',
};
